export const CATEGORY_ID_BY_NAME: Record<string, number> = {
  "Web Development": 1,
  "Mobile Development": 2,
  "Game Development": 3,
  "Data Science": 4,
  "Machine Learning": 5,
  "Deep Learning": 6,
  "Artificial Intelligence": 7,
  "Cloud Computing": 8,
  "DevOps": 9,
  "Cybersecurity": 10,
  "Blockchain": 11,
  "Internet of Things": 12,
  "Software Engineering": 13,
  "Programming Fundamentals": 14,
  "Algorithms and Data Structures": 15,
  "Operating Systems": 16,
  "Computer Networks": 17,
  "Databases": 18,
  "Big Data": 19,
  "Information Theory": 20,
  "Discrete Mathematics": 21,
  "Linear Algebra": 22,
  "Calculus": 23,
  "Probability and Statistics": 24,
  "Optimization": 25,
  "Numerical Methods": 26,
  "Physics": 27,
  "Chemistry": 28,
  "Biology": 29,
  "Electrical Engineering": 30,
  "Mechanical Engineering": 31,
  "Civil Engineering": 32,
  "Business and Management": 33,
  "Entrepreneurship": 34,
  "Marketing": 35,
  "Finance and Accounting": 36,
  "Project Management": 37,
  "Product Management": 38,
  "UI Design": 39,
  "UX Design": 40,
  "Graphic Design": 41,
  "3D Modeling and Animation": 42,
  "Video Production": 43,
  "Photography": 44,
  "Music Production": 45,
  "Language Learning": 46,
  "English Language": 47,
  "Test Preparation": 48,
  "Personal Development": 49,
  "Leadership and Management Skills": 50,
  "Soft Skills": 51,
  "Career Development": 52,
  "Teaching and Instructional Design": 53,
  "Health and Wellness": 54,
  "Lifestyle and Hobbies": 55,
  "Programming in Python": 56,
  "Programming in Java": 57,
  "Programming in JavaScript": 58,
  "Mobile Development with Flutter": 59,
  "Backend Development": 60,
  "Frontend Development": 61,
  "Data Engineering": 62,
  "Cloud Architecture": 63,
  "Ethical Hacking": 64,
  "UI/UX for Mobile Apps": 65,
  "No-Code and Low-Code": 66,
  "Office Productivity": 67,
  "Human Resources": 68,
  "Legal and Compliance": 69,
  "Sales": 70,
  "Customer Support": 71,
  "Research Methods": 72,
  "Academic Skills": 73,
  "Data Visualization": 74,
  "Cybersecurity for Developers": 75,
  "Cloud DevOps": 76,
  "AI in Business": 77,
  "Prompt Engineering": 78,
  "Ethics in Technology": 79,
  "Digital Transformation": 80,
  "E-Learning Content Creation": 81,
  "Language Teaching": 82,
  "Mathematical Foundations for ML": 83,
  "Competitive Programming": 84,
  "System Design": 85,
  "API Design": 86,
  "AR and VR Development": 87,
  "Robotics": 88,
  "Embedded Systems": 89,
  "Quantum Computing": 90,
  "Human-Computer Interaction": 91,
  "Knowledge Management": 92,
  "Digital Art": 93,
  "Copywriting": 94,
  "Content Creation": 95,
  "Social Media Marketing": 96,
  "SEO": 97,
  "Analytics and Measurement": 98,
  "Time Management": 99,
  "Mindfulness and Mental Health": 100
};
